spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      # 1024*1024*10
      max-file-size: 10485760
      max-request-size: 10485760
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true

server:
  port: 9201
  servlet:
    context-path: ""

# mybatis
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/tea/movie/play/bgd/frisbee/mapper/*.xml # ** 表示可多级目录

# dubbo
dubbo:
  registry:
    address: spring-cloud://localhost
    register: false # 只订阅不注册
  protocol:
    name: dubbo
    port: 20902
    host: 192.168.1.105
  cloud:
    subscribed-services: uac-provider
  consumer:
    check: false



#数据库密码加密
jasypt:
  encryptor:
    password: c2h1anVrdXpoaW5pY2FpY2Fpa2Fu
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator